"""Food model added

Revision ID: 8b4d75915273
Revises: 
Create Date: 2019-08-22 19:12:20.323882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4d75915273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('cn_description', sa.String(length=500), nullable=True))
    op.add_column('food', sa.Column('inUse', sa.Boolean(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('food', 'inUse')
    op.drop_column('food', 'cn_description')
    # ### end Alembic commands ###
