"""sdasdsadsa

Revision ID: 91642a4dc210
Revises: 
Create Date: 2019-09-26 19:10:22.638930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91642a4dc210'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('is_a_la_carte', sa.Boolean(), nullable=True))
    op.add_column('food', sa.Column('is_buffet', sa.Boolean(), nullable=True))
    op.add_column('food', sa.Column('is_takeaway', sa.Boolean(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('food', 'is_takeaway')
    op.drop_column('food', 'is_buffet')
    op.drop_column('food', 'is_a_la_carte')
    # ### end Alembic commands ###
